### ISSUE TITLE
Is there another script to avoid using Cuda?

### ISSUE THREAD

**Issue by fylinhub** [wengong-jin/hgraph2graph#2]
Never mind; I've figured out how to modify it.

**Comment by aasimayazwani** [comment]
what did you do, to go around Cuda ?

**Comment by ShayneWierbowski** [comment]
> what did you do, to go around Cuda ?

Have not fully tested this myself (only tested on the generate.py script so far), but I'm testing a similar CPU only setup. First I removed all instances of ".cuda()" function call. And then had to update the line where the checkpoint model is loaded.

### Original Code (generate.py line 44)
`model.load_state_dict(torch.load(args.model))[0])`

### Modified Code
`model.load_state_dict(torch.load(args.model, map_location=torch.device('cpu'))[0])`

To replace all the ".cuda()" calls you can run the following from the root of the git clone...

`find . -type f -name "*.py" -exec sed -i'' -e 's/\.cuda()//g' {} +`

This seems to be all that is needed, however depending on your use case there could still be other places that need to be modified.
