### ISSUE TITLE
Out-of-memory occurs at preprocessing training data

### ISSUE THREAD

**Issue by hwidong-na** [wengong-jin/hgraph2graph#22]
Hi,

I got an unexpected error due to the memory consumption during preprocessing.

Environment:
numpy 1.19.2
python 3.7.10
pytorch 1.8.0
rdkit 2020.09.1.0
Mem: 64GB

Any suggestions?

Best,
Hwidong

**Comment by hwidong-na** [comment]
Using a machine with larger memory solved this issue.

**Comment by mpds** [comment]
How much memory did you need to run it?
