### ISSUE TITLE
no gnn_train.py in generation folder

### ISSUE THREAD

**Issue by HayeonLee** [wengong-jin/hgraph2graph#6]
Thank you for your interesting work.

For generation task, 
In Readme, 
`mkdir -p ckpt/tmp`
`python gnn_train.py --train train_processed/ --vocab ../data/polymers/inter_vocab.txt --save_dir ckpt/tmp`

but there is no 'gnn_train.py' in generation folder.
Could you check this? thank you in advance!

**Comment by wengong-jin** [comment]
It should be vae_train.py. That was a typo when the README was edited. It has been corrected now. Thank you!
